### ISSUE TITLE
перевірка

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/JSArray#1]
https://github.com/VasylUlianovskyi/JSArray/blob/dd77403ecdb00370ce97e4a4814ce36189d17928/assets/js/array.js#L68
- "або видати діагностичне повідомлення, якщо такого елементу не існує" 
Тут треба згадати, що повертає `findIndex`, якщо шуканого елементу не існує

**Comment by VasylUlianovskyi** [comment]
++
