### ISSUE TITLE
умова завдання

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/JSArray#3]
https://github.com/VasylUlianovskyi/JSArray/blob/dd77403ecdb00370ce97e4a4814ce36189d17928/assets/js/array.js#L45
https://github.com/VasylUlianovskyi/JSArray/blob/dd77403ecdb00370ce97e4a4814ce36189d17928/assets/js/array.js#L50
- трохи неуважно прочитали умову. Зараз некритично, а от на роботі було б невесело)

**Comment by VasylUlianovskyi** [comment]
++
