### ISSUE TITLE
спосіб запису

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/JSArray#4]
https://github.com/VasylUlianovskyi/JSArray/blob/dd77403ecdb00370ce97e4a4814ce36189d17928/assets/js/usersArray.js#L36
- порівняння з хибою буде логічно записати так:
```javascript
const notSubscribedUsers = users.filter((user) => !user.isSubscribed);
```

**Comment by pecourses** [comment]
https://github.com/VasylUlianovskyi/JSArray/blob/dd77403ecdb00370ce97e4a4814ce36189d17928/assets/js/usersArray.js#L48
https://github.com/VasylUlianovskyi/JSArray/blob/dd77403ecdb00370ce97e4a4814ce36189d17928/assets/js/usersArray.js#L76
https://github.com/VasylUlianovskyi/JSArray/blob/dd77403ecdb00370ce97e4a4814ce36189d17928/assets/js/usersArray.js#L109
- аналогічно

**Comment by VasylUlianovskyi** [comment]
++
